language: node_js
node_js:
  - "lts/*"

notifications:
  slack:
    secure: "QCa/e5P2+zk+VolQxxOgsSlFul7tuMG/g/n4tlCc9kdVdIgvKtzqv3uzFw8nF5z49x9l8PsWWHmHNaypIg83s3ciZoIplr8baaqOSZEmiAB4rmN/u+10L5uRIYngBOEHpICP/YrfMFaqL2JoIhNcTUwuULfCNoSsdmKnbR01EfYZn+93Bj7t1mm5sNBeJNqbLi7ERVgHml8QqCJ6RBcu2s+dR+j+2du7U2+u7wcwoYgLh6zAnXwVHKvp49+UepXu5OpSauY3CnivZMz+uDA5iP6ZbMFXtOggadJedskMfAvCUzU+8oXTexZtWcsREMXS6AxOkQg8qZ8YSVGeyh11Ae0E4/sSNns0uh7VrtPtLk7Hq4KHi5LTgY1UF+A98zOzLsWbiIBGtYc6HSUmm4k9lgYOQkwU//Pl+3Phn5Pj+NMbvSTxKOJREfqotuxhoKbu/5m6Y/FXhRDLJ5RIZLYG08fPcgld1qh10m03ZgOhrciSdCZxZhNpkfpfvLlMa3WkyiSSS5F9BWrsNETpDg351RO13T/RE+yadymUO5x8UDG1w82UvRMO3GXifdQaeHmPEA28Z32w0/07o4z8q6A7n7mIW7oqYqE6Xck54fXn6sDvGPbB5RtL4SRVYqvgMNS4x8C9zvysBz8oFp5dI26cIc2qdiIrC2WfntGkVr064lg="
